<div class="container wraper">
  <!--  <div class="content-spacing margin-top-bottom">
        <div class="row">            
            <?php $this->load->view('site/theme/menu') ?>

            <div class="col-sm-6 content-spacing">
                <div class="midd-bar">
                    <div class="recent-post-box clearfix">
                        <h1>Keynote Speech 4</h1>

                        <p class="img-left">
                        <p style="text-align: center;"><strong>The International Year of Light 2015 and Light-based Technologies – An Introspection</strong></p>
                        <p style="text-align: center;">Bishnu P. Pal<sup>*</sup></p>
                        <p style="text-align: center;">School of Natural Sciences</p>
                        <p style="text-align: center;">Mahindra École Centrale College of Engineering</p>
                        <p style="text-align: center;">Hyderabad: 500043</p>
                        <p style="text-align: center;">India</p>
                        <p style="text-align: center;"><sup>*</sup>Email: bishnu.pal@mechyd.ac.in</p>
                        <p style="text-align: justify;"><strong>Abstract: </strong>In this talk I would discuss through examples how optical science influenced emergence of the fundamental science of quantum mechanics, often provide solutions to global challengesin communications,energy, education, agriculture, and health care. The year 2015 coincides with anniversaries of several important milestones in the history of the science of light for example,the work of Ibn Al-Haytham from Egypt in 1015, proposal of light as a wave by Fresnel in 1815, electromagnetic nature of light as proven by Maxwell in 1865,Einstein’s Nobel prize winning work on Photoelectric Effect in 1905 and thetheory of general relativity in 1915 that embeds light in explaining certain aspects of cosmology, discovery of cosmic microwave background by Penzias and Wilson, and Charles Kao’s demonstrationof glass fibers as a potential medium for optical transmission of signals for telecommunication &#8211; both in1965.Light-based technologies indeed vey significantly play extremely important roles for our instant access to the Internet from anywhere any time before possibly we could complete blinking of our eye! I will also present few of my recent research on mid-IR photonics and specialty optical fiber designs for THz generation and transmission.</p>
                        <p>&nbsp;</p>
                        <p><strong>Short Biography of the Speaker:</strong></p>
                        <p><strong><a href="#"><img class="aligncenter size-full wp-image-392" src="<?=$assets?>images/Bishnu_P.png" alt="Bishnu_P" width="92" height="108" /></a></strong></p>
                        <p style="text-align: justify;">Bishnu P. Pal is currently Professor of Physics at the School of Natural Sciences in Mahindra Ecole Centrale at Hyderabad India (www.mahindraecolecentrale.edu.in). Before joining this newly established college of Engineering in collaboration with Ecole Centrale Paris of France, he was a Professor of Physics for over 24 years (and as a Physics faculty member for about 34 years) at the Indian Institute of Technology Delhi, where he served as the Chairperson of the Physics Department (September 2008-December 2011) and also the Computer Services Center (September 2003-August 2006). He was deeply involved in introducing and developing the interdisciplinary M. Tech. program on Optoelectronics and Optical Communication in 1980 at IIT Delhi.  One of his research papers published in 1980 in Electronics Letters was reprinted in the IEE book “Progress in Optical Communication Vol. II” ed by P J B Clarricoats and two of his authored/co-authored chapters from his edited book “Guided Wave Optical Components and Devices- Basics, Technology and Applications” (Academic Press, 2006) were reprinted in the book “The Optical Communications reference (edsDeCusatis and Kaminow, Academic Press), which contains a collection of select chapters from a number of authoritative sources from Academic Press’s range of prestigious book titles in optical communications.</p>
                        <p style="text-align: justify;">He has edited several books published by Elsevier/Academic Press, John Wiley, Intech, Viva publishers. He has also contributed over 15 chapters – all by invitation in various books. Prof Pal has extensively contributed to sponsored research and industrial consultancy and especially several international collaborative research projects that involved UK, USA, Russia, France, and Hong Kong.His current areas of research is Guided Wave Optics and Optical Communication that broadly covers application-specific specialty optical fibers like dispersion compensating fibers, dispersion shifted fibers, fibers for inherently gain flattened fiber amplifiers, large mode area fibers and fibers for DWDM transmission, All-fiber components and devices like fused fiber and side-polished fiber couplers, wavelength interleavers as branching components for super-DWDM optical communication networks, designs of new generation microstructured optical fibers for supercontinuum light, dispersion compensation, metro optical networks, mid-infrared photonics, and also for THz generation and transmission, optical fiber sensors, and Anderson type localization of light in a disordered optical waveguide lattice.</p>
                        <p style="text-align: justify;">Prof Pal has worked as a guest scientist at ELAB at NTH Trondheim in Norway as NTNF Fellow, CNRS laboratory LPMC at University of Nice in France as Senior Foreign Scientist of CNRS for various periods, NIST Boulder Colorado in USA as a Fulbright Scholar, Heriot Watt University Edinburgh in UK as an Erasmus Mundus Scholar in Photonics, City U Hong Kong and University of Malay at Kuala Lumpur in Malaysia as Visiting Professor for various periods, and at Fraunhofer Institute for PhysikalischeMesstechnik in Freiburg (Germany) as an Alexander von Humboldt Fellow. He has been a founding member of Int. J. Optoelectron. (Taylor &amp; Francis) and is currently a Member of the Editorial Advisory Boards of the journals: J. Opt. Comm. (Germany), J. Elect. Engg.&amp; Tech. (Korea), Optoelectron.Letts. (China), J. Korean Opt. Soc. (Korea), Photonic Sensors (Springer), Journal of Electromagnetic Waves and Applications (Taylor &amp; Francis) and Kiran of the Indian Laser Society.</p>
                        <p style="text-align: justify;">He has published and reported over 190 research papers and research reviews in peer reviewed international journals and conferences and has co-authored one each Indian and US patents. Prof. Pal is a Fellow of OSA The Optical Society (USA) and SPIE (USA), Honorary Foreign Member of the Royal Norwegian Academy of Sciences and Letters (DKNVS, Norway), and Senior Member of IEEE (USA). He is a co-recipient of the First Fiber Optic Person of the Year award in 1997 instituted by Lucent Technology in India, Distinguished Lecturer of IEEE Photonics Society (formerly LEOS) USA for 2005-2007 during which he had extensively travelled and lectured around the world on his research, recipient of the HomiBhabha Award of UGC (India) for excellence in Applied Sciences for 2006, OSI (India) Life Time Achievement award (2010), Prof Y. T Thathachari Prestigious Research Award in Physical Science of Bhramara Trust Mysore for 2010, CEOT 2010 award of IETE (India), Om Prakash Bhasin National award for Electronics and Information Technology 2013, and more recently Khosla National Research Award 2014 of IIT Roorkee for life time achievements in India.</p>
                        <p style="text-align: justify;">Prof. Pal was President of the Optical Society of India (2012-2014), a Member of the Board of Directors (2009-2011) of OSA The Optical Society (USA), its International Council (2007-2009), and Long Term Planning Group (2010-15) for publications, Associate Vice-President of the Membership Council of IEEE Photonics Society.</p>

                        <hr/>
                    </div>

                    <div class="navigation">
                        <strong><p></p></strong>
                    </div>
                </div>
            </div>
            
            <?php $this->load->view('site/theme/sidebar') ?>
        </div>
    </div>-->
This link is currently off.
</div>